sudo: required
services: 
  - docker

before_install:
  - docker build -t dquez/game-of-life -f Dockerfile.dev .
# getting multiple "Cannot find module './Board.js' from 'App.js'"", but tests work locally
script:
  - docker run dquez/game-of-life npm run test -- --coverage


